/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package creditcard.views;

import creditcard.factory.CreditCardFactory;
import framework.IParty;
import framework.Invoker;
import framework.Receiver;
import framework.command.AddDefaulAccountCommand;
import framework.command.ICommand;
import framework.view.DefaultAccountForm;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author javkhlant
 */
public class CreditCardAccountForm extends JDialog {

    JLabel JLabel1 = new JLabel();
    JLabel JLabel2 = new JLabel();
    JLabel JLabel3 = new JLabel();
    JLabel JLabel4 = new JLabel();
    JLabel JLabel5 = new JLabel();
    JLabel JLabel6 = new JLabel();
    JLabel JLabel7 = new JLabel();
    JLabel JLabel8 = new JLabel();
    JLabel JLabel9 = new JLabel();
    JLabel JLabel10 = new JLabel();
    JTextField JTextField_NAME = new JTextField();
    JTextField JTextField_CT = new JTextField();
    JTextField JTextField_ST = new JTextField();
    JTextField JTextField_STR = new JTextField();
    JTextField JTextField_ZIP = new JTextField();
    JTextField JTextField_EM = new JTextField();
    JTextField ccNumberField = new JTextField();
    JTextField expireDateField = new JTextField();
    JButton JButton_OK = new JButton();
    JButton JButton_Calcel = new JButton();
    JTextField JTextField_ACNR = new JTextField();
    JRadioButton JRadioButton_Gold = new JRadioButton();
    JRadioButton JRadioButton_Silver = new JRadioButton();
    JRadioButton JRadioButton_Bronze = new JRadioButton();

    private String AccountNumber;
    private String name;
    private String street;
    private String city;
    private String state;
    private String zip;
    private String email;
    private String ccNumber;
    private Date expireDate;
    private String type;
    private final SimpleDateFormat dateFormat;

    private DefaultAccountForm defaultAcc;
    private Invoker invoker;
    private Receiver receiver;

    public CreditCardAccountForm(Invoker invoker, Receiver receiver) {
        this.invoker = invoker;
        this.receiver = receiver;
        this.dateFormat = new SimpleDateFormat("MM/dd/yyyy");
        //defaultAcc = new DefaultAccountForm();

        //new DefaultAccountForm();
        // This code is automatically generated by Visual Cafe when you add
        // components to the visual environment. It instantiates and initializes
        // the components. To modify the code, only use code syntax that matches
        // what Visual Cafe can generate, or Visual Cafe may be unable to back
        // parse your Java file into its visual environment.
        //{{INIT_CONTROLS
        setTitle("Add Credit Card Account");
        setModal(true);
        getContentPane().setLayout(null);
        setSize(400, 550);
        setVisible(false);

        JRadioButton_Gold.setText("Gold");
        JRadioButton_Gold.setActionCommand("Checkings");
        getContentPane().add(JRadioButton_Gold);
        JRadioButton_Gold.setBounds(36, 12, 84, 24);

        JRadioButton_Silver.setText("Silver");
        JRadioButton_Silver.setActionCommand("Savings");
        getContentPane().add(JRadioButton_Silver);
        JRadioButton_Silver.setBounds(36, 36, 84, 24);

        JRadioButton_Bronze.setText("Bronze");
        JRadioButton_Bronze.setActionCommand("Savings");
        getContentPane().add(JRadioButton_Bronze);
        JRadioButton_Bronze.setBounds(36, 60, 84, 24);
        JRadioButton_Bronze.setSelected(true);
        type = JRadioButton_Bronze.getText();

        
        JLabel10.setText("Account Nr");
        getContentPane().add(JLabel10);
        JLabel10.setForeground(java.awt.Color.black);
        JLabel10.setBounds(12, 84, 60, 24);

        JLabel1.setText("Name");
        getContentPane().add(JLabel1);
        JLabel1.setForeground(java.awt.Color.black);
        JLabel1.setBounds(12, 108, 60, 24);

        JLabel2.setText("Street");
        getContentPane().add(JLabel2);
        JLabel2.setForeground(java.awt.Color.black);
        JLabel2.setBounds(12, 132, 48, 24);

        JLabel3.setText("City");
        getContentPane().add(JLabel3);
        JLabel3.setForeground(java.awt.Color.black);
        JLabel3.setBounds(12, 156, 48, 24);

        JLabel4.setText("State");
        getContentPane().add(JLabel4);
        JLabel4.setForeground(java.awt.Color.black);
        JLabel4.setBounds(12, 180, 48, 24);

        JLabel5.setText("Zip");
        getContentPane().add(JLabel5);
        JLabel5.setForeground(java.awt.Color.black);
        JLabel5.setBounds(12, 204, 48, 24);

        JLabel7.setText("Email");
        getContentPane().add(JLabel7);
        JLabel7.setForeground(java.awt.Color.black);
        JLabel7.setBounds(12, 228, 48, 24);

        JLabel8.setText("CC number");
        getContentPane().add(JLabel8);
        JLabel8.setForeground(Color.black);
        JLabel8.setBounds(12, 252, 96, 24);

        JLabel9.setText("Expire date");
        getContentPane().add(JLabel9);
        JLabel9.setForeground(Color.black);
        JLabel9.setBounds(12, 276, 144, 24);

        getContentPane().add(JTextField_ACNR);
        JTextField_ACNR.setBounds(120, 84, 156, 20);
        getContentPane().add(JTextField_NAME);
        JTextField_NAME.setBounds(120, 108, 156, 20);
        getContentPane().add(JTextField_CT);
        JTextField_CT.setBounds(120, 132, 156, 20);
        getContentPane().add(JTextField_ST);
        JTextField_ST.setBounds(120, 156, 156, 20);
        getContentPane().add(JTextField_STR);
        JTextField_STR.setBounds(120, 180, 156, 20);
        getContentPane().add(JTextField_ZIP);
        JTextField_ZIP.setBounds(120, 204, 156, 20);
        getContentPane().add(JTextField_EM);
        JTextField_EM.setBounds(120, 228, 156, 20);
        getContentPane().add(ccNumberField);
        ccNumberField.setBounds(120, 252, 156, 20);
        getContentPane().add(expireDateField);
        expireDateField.setBounds(120, 276, 156, 20);
        expireDateField.setText(dateFormat.format(new Date()));
        expireDateField.setEditable(false);
        JButton_OK.setText("OK");
        JButton_OK.setActionCommand("OK");
        getContentPane().add(JButton_OK);
        JButton_OK.setBounds(48, 312, 84, 24);
        JButton_Calcel.setText("Cancel");
        JButton_Calcel.setActionCommand("Cancel");
        getContentPane().add(JButton_Calcel);
        JButton_Calcel.setBounds(156, 312, 84, 24);
		//}}

        //{{REGISTER_LISTENERS
        SymAction lSymAction = new SymAction();
        JButton_OK.addActionListener(lSymAction);
        JButton_Calcel.addActionListener(lSymAction);
        SymMouse aSymMouse = new SymMouse();
        JRadioButton_Gold.addMouseListener(aSymMouse);
        JRadioButton_Silver.addMouseListener(aSymMouse);
        JRadioButton_Bronze.addMouseListener(aSymMouse);
        //}}
    }

    class SymMouse extends java.awt.event.MouseAdapter {

        public void mouseClicked(java.awt.event.MouseEvent event) {
            Object object = event.getSource();
            if (object == JRadioButton_Gold) {
                JRadioButtonChk_mouseClicked(event);
            } else if (object == JRadioButton_Silver) {
                JRadioButtonSav_mouseClicked(event);
            } else if (object == JRadioButton_Bronze) {
                JRadioButtonBronze_mouseClicked(event);
            }

        }
    }

    void JRadioButtonChk_mouseClicked(java.awt.event.MouseEvent event) {
        type = JRadioButton_Gold.getText();
        JRadioButton_Gold.setSelected(true);
        JRadioButton_Silver.setSelected(false);
        JRadioButton_Bronze.setSelected(false);
    }

    void JRadioButtonSav_mouseClicked(java.awt.event.MouseEvent event) {
        type = JRadioButton_Silver.getText();
        JRadioButton_Gold.setSelected(false);
        JRadioButton_Silver.setSelected(true);
        JRadioButton_Bronze.setSelected(false);
    }

    void JRadioButtonBronze_mouseClicked(java.awt.event.MouseEvent event) {
        type = JRadioButton_Bronze.getText();
        JRadioButton_Gold.setSelected(false);
        JRadioButton_Silver.setSelected(false);
        JRadioButton_Bronze.setSelected(true);
    }

    class SymAction implements ActionListener {

        public void actionPerformed(ActionEvent event) {
            Object object = event.getSource();
            if (object == JButton_OK) {
                JButtonOK_actionPerformed(event);
            } else if (object == JButton_Calcel) {
                JButtonCalcel_actionPerformed(event);
            }
        }
    }

    void JButtonOK_actionPerformed(ActionEvent event) {
        if (!JTextField_ACNR.getText().isEmpty()) {
            AccountNumber = JTextField_ACNR.getText();
            name = JTextField_NAME.getText();
            street = JTextField_STR.getText();
            city = JTextField_CT.getText();
            state = JTextField_ST.getText();
            zip = JTextField_ZIP.getText();
            email = JTextField_EM.getText();
            ccNumber = ccNumberField.getText();
            try {
                expireDate = dateFormat.parse(expireDateField.getText());
            } catch (ParseException ex) {
                Logger.getLogger(CreditCardAccountForm.class.getName()).log(Level.SEVERE, null, ex);
            }

            CreditCardFactory factory = new CreditCardFactory();
            IParty customer = factory.createCustomer(this);

            ICommand addDefault = new AddDefaulAccountCommand(customer);
            invoker.submit(addDefault);
    //        this.receiver.print();
            dispose();
        }
    }

    void JButtonCalcel_actionPerformed(java.awt.event.ActionEvent event) {
        dispose();
    }

    public String getAccountNumber() {
        return AccountNumber;
    }

    public String getStreet() {
        return street;
    }

    public String getCity() {
        return city;
    }

    public String getState() {
        return state;
    }

    public String getZip() {
        return zip;
    }

    public String getEmail() {
        return email;
    }

    @Override
    public String getName() {
        return name;
    }

    public String getCcNumber() {
        return ccNumber;
    }

    public Date getExpireDate() {
        return expireDate;
    }

    public String getCardType() {
        return type;
    }
}